Repository JuiceMitApfelnDrin/CodinCodFrontend, pull requests merged in 2024-09, with the labels that each got.

#18 fix: use `backendUrls` in registration flow
  src/lib/features/register/api/check-username-availability.ts
  src/routes/register/+page.server.ts
Labels: bug

#21 centralize & simplify logic for changing theme
  src/lib/components/nav/toggle-theme.svelte
  src/routes/+layout.svelte
  src/stores.ts
Labels: bug, enhancement

#23 feat/issue-22: test progression bar
  src/app.css
  src/lib/components/nav/logged-in-nav.svelte
  src/lib/components/nav/logged-out-nav.svelte
  src/lib/components/nav/logout-button.svelte
  src/lib/components/ui/accordion/accordion-content.svelte
  src/lib/components/ui/accordion/accordion-item.svelte
  src/lib/components/ui/accordion/accordion-trigger.svelte
  src/lib/components/ui/accordion/accordion.svelte
  src/lib/components/ui/accordion/index.ts
  src/lib/features/game/components/codemirror.svelte
  src/lib/features/puzzles/components/create-puzzle-form.svelte
  src/lib/features/puzzles/components/test-progress-bar.svelte
  src/lib/features/puzzles/components/validator-status.svelte
  src/lib/utils/calculate-puzzle-result-color.ts
  src/routes/+page.svelte
  src/routes/puzzles/[id]/play/+page.svelte
  src/routes/puzzles/create/+page.server.ts
  src/routes/register/+page.server.ts
Labels: enhancement

#24 fix: authentication flow
  src/app.css
  src/lib/components/nav/logged-in-nav.svelte
  src/lib/components/nav/logged-out-nav.svelte
  src/lib/components/nav/logout-button.svelte
  src/lib/components/nav/nav.svelte
  src/lib/components/nav/toggle-theme.svelte
  src/lib/components/ui/alert/index.ts
  src/lib/components/ui/form/form-field-errors.svelte
  src/lib/components/ui/form/form-label.svelte
  src/lib/config/unprotectedRoutes.ts
  src/lib/features/authentication/login/api/login.ts
  src/lib/features/authentication/login/components/login-form.svelte
  src/lib/features/authentication/register/api/check-username-availability.ts
  src/lib/features/authentication/register/components/register-form.svelte
  src/lib/features/authentication/register/config/register-form-schema.ts
  src/lib/features/authentication/utils/fetch-with-authentication-cookie.ts
  src/lib/features/authentication/utils/get-authenticated-user-info.ts
  src/lib/features/authentication/utils/get-cookie.ts
  src/lib/features/authentication/utils/logout.ts
  src/lib/features/authentication/utils/set-cookie.ts
  src/lib/features/puzzles/api/delete-puzzle.ts
  src/lib/stores/index.ts
  src/lib/utils/is-protected-route.ts
  src/routes/(authenticated)/+layout.server.ts
  src/routes/(authenticated)/game/.gitkeep
  src/routes/(authenticated)/puzzles/[id]/edit/+page.server.ts
  src/routes/(authenticated)/puzzles/[id]/edit/+page.svelte
  src/routes/(authenticated)/puzzles/[id]/edit/+page.ts
  src/routes/(authenticated)/puzzles/[id]/play/+page.server.ts
  src/routes/(authenticated)/puzzles/[id]/play/+page.svelte
  src/routes/(authenticated)/puzzles/create/+page.server.ts
  src/routes/(authenticated)/puzzles/create/+page.svelte
  src/routes/(authenticated)/settings/+page.svelte
  src/routes/(unauthenticated-only)/+layout.server.ts
  src/routes/(unauthenticated-only)/login/+page.server.ts
  src/routes/(unauthenticated-only)/login/+page.svelte
  src/routes/(unauthenticated-only)/register/+page.server.ts
  src/routes/(unauthenticated-only)/register/+page.svelte
  src/routes/+layout.server.ts
  src/routes/+layout.svelte
  src/routes/login/+page.svelte
  src/routes/register/+page.svelte
Labels: enhancement
